version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - dependencies
  - dependabot
  versioning-strategy: increase
  allow:
  - dependency-name: dreamfactory/df*
